version: "3"
services:
  node: 
    build: .
    ports: 
      - 3000:3000
    command: npm start
    depends_on: 
      - db
    env_file: .env
    environment:
      - DB_HOST=db
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"
volumes:
  db_data: