version: "3"
services:
  node: 
    build: .
    ports: 
      - 3000:3000
    command: npm start
    depends_on: 
      - db
    environment:
      - DB_URL=${DB_URL}
      - PORT=3000
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}